version: '3.8'
services:
  api:
    container_name: todoapp-api
    # networks:
    #   - nestjs-crud
    #   - postgres-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      postgresdb:
        condition: service_healthy

  postgresdb:
    image: postgres:13
    # networks:
    #   - postgres-db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
# networks:
#   nestjs-crud:
#   postgres-db:
