version: '3.8'
services:
  todo-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todoapp-db
    networks:
      - todoapp-api-network
networks:
  todoapp-api-network:
