version: '3.8'
services:
  api:
    container_name: todoapp-api
    networks:
      - nestjs-crud
      - postgres-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333

  postgresdb:
    image: postgres:13.5
    networks:
      - postgres-db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:

networks:
  nestjs-crud:
  postgres-db:
